### ISSUE TITLE
Freemember Login Doesn't Work (example from docs) EE2.9.0

### ISSUE THREAD

**Issue by JamesMcFall** [devdemon/freemember#81]
After trying a couple of implementations of the login form without luck I went back to the default example from the docs. I still can't get it to work.

To be safe I tried clearing cookies (not the issue) as well as checking for JS errors in case it was interfering with the ajax. No dice.

**Symptoms**
What happens is regardless of whether the credentials are correct or not, the page reloads and just shows the login form again.

**EE Version & Plugins**

* EE V2.9.0 - Build Date: 20140715 
* Freemember 2.3.2
* I am using Structure, in case that's relevant.

**Comment by JamesMcFall** [comment]
I have found the problem and it wasn't related to your plugin. An **.htaccess rule adding a trailing slash** was causing this to fail. As soon as that was removed it started working again. Sorry about that!

**Comment by lexbi** [comment]
@JamesMcFall I had that issue in another cms once upon a time, you can keep what you had but add a condition to not do it on POST
